apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contador
  template:
    metadata:
      labels:
        app: contador
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - name: default-container
<<<<<<< HEAD
          image: ghcr.io/emilioamvs/contador
=======
          image: ghcr.io/EmilioamvS/contador:91090eb
>>>>>>> 0ac45abe6556d440d2af2c93224e001535738984
          ports:
            - containerPort: 8080
