apiVersion: apps/v1
kind: Deployment
metadata:
  name: contador-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contador
  template:
    metadata:
      labels:
        app: contador
    spec:
      containers:
        - name: default-container
          image: ghcr.io/emilioamvs/contador:5d26f9d
          ports:
            - containerPort: 80
