apiVersion: apps/v1
kind: Deployment
metadata:
  name: contador-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contador
  template:
    metadata:
      labels:
        app: contador
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - name: default-container
          image: ghcr.io/emilioamvs/contador:c187184
          ports:
            - containerPort: 80
