apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  namespace: default
spec:
  selector:
    app: contador
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
