apiVersion: v1
kind: Service
metadata:
  name: contador-service
  namespace: default
spec:
  selector:
    app: contador
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80       # Ajusta esto al puerto que tu aplicación escucha
      nodePort: 30340      # (opcional) puedes dejar que Kubernetes lo asigne automáticamente
